field: 58b2e318-26cc-47b8-bee2-81369731d72f # Body Content
fieldLayouts:
  54740fa7-c999-46cf-ac6d-9d485820899c:
    tabs:
      -
        elements:
          -
            fieldUid: b026d20d-f781-469f-8c4c-5f5c65c66027 # Target
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9a20f22f-7c49-4e40-85a3-58b7d7e26bf7
            warning: null
            width: 25
          -
            fieldUid: fa76440e-c84c-4d11-b665-375f32514aaa # Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1abf18e1-4ac7-4c7f-872b-7fb7d47c5096
            warning: null
            width: 25
        name: Content
        uid: ca1b793f-57b3-4339-a323-6537156d40be
fields:
  b026d20d-f781-469f-8c4c-5f5c65c66027: # Target
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: target
    instructions: null
    name: Target
    searchable: true
    settings:
      allowSelfRelations: false
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: 'Select an entry'
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  fa76440e-c84c-4d11-b665-375f32514aaa: # Caption
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: caption
    instructions: 'Leave blank to show title of target'
    name: Caption
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: button
name: Button
sortOrder: 6
