field: ae7d91c8-8743-46bb-a954-438a27946b97 # Primary Navigation
fieldLayouts:
  a488e318-6b3c-4902-a35a-f96636141ea6:
    tabs:
      -
        elements:
          -
            fieldUid: c6943610-b0b4-4588-88b9-c13480f83557 # Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cb2e87e0-4c2d-4ffe-a50c-22b703b7d1ab
            warning: null
            width: 100
          -
            fieldUid: 91e82c8e-91b5-456d-a06b-bd9e86bb5059 # Entries
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e91d3deb-ad44-4c33-b0ea-3ab7555daf2a
            warning: null
            width: 100
        name: Content
        uid: f52ebc2c-010e-48fb-95fd-4f5de5afbc1e
fields:
  91e82c8e-91b5-456d-a06b-bd9e86bb5059: # Entries
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: entries
    instructions: null
    name: Entries
    searchable: false
    settings:
      allowSelfRelations: false
      localizeRelations: false
      maxRelations: null
      minRelations: null
      selectionLabel: null
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  c6943610-b0b4-4588-88b9-c13480f83557: # Caption
    columnSuffix: null
    contentColumnType: string(120)
    fieldGroup: null
    handle: caption
    instructions: null
    name: Caption
    searchable: false
    settings:
      byteLimit: null
      charLimit: 30
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
handle: dropDown
name: 'Drop Down'
sortOrder: 2
