field: 58b2e318-26cc-47b8-bee2-81369731d72f # Body Content
fieldLayouts:
  070f840f-c5bc-4bd3-ad32-c6a5d55d9e3c:
    tabs:
      -
        elements:
          -
            fieldUid: c7d0c14f-5533-4bdc-863d-cedbbb544960 # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3330f7cb-0744-4366-ba26-91bb5ed4d228
            warning: null
            width: 75
        name: Content
        uid: 8d22c5a9-7386-4bfe-9d2e-6533be04082a
fields:
  c7d0c14f-5533-4bdc-863d-cedbbb544960: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: heading
name: Heading
sortOrder: 1
