field: 58b2e318-26cc-47b8-bee2-81369731d72f # Body Content
fieldLayouts:
  5019c24d-309a-4ed8-8c94-f62cf5fbbf1b:
    tabs:
      -
        elements:
          -
            fieldUid: 7a11b052-f8c9-46d7-8bb4-7c9a3916200c # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 93209b03-fb78-452b-a1cf-3f76147a807b
            warning: null
            width: 25
          -
            fieldUid: d80ee1f4-e752-4e38-860a-c5f26790bf89 # Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 80b49532-b3df-489e-a87a-488f35efb2da
            warning: null
            width: 50
        name: Content
        uid: 5c8d8db9-8f4a-4e17-993e-458a8cdbc46d
fields:
  7a11b052-f8c9-46d7-8bb4-7c9a3916200c: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: 'Double click to edit title, copyright and focus point of the image'
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:8136d7e9-1a74-464d-aef2-3a4f91a5cdda' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:8136d7e9-1a74-464d-aef2-3a4f91a5cdda' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Select an image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      source: null
      sources:
        - 'volume:8136d7e9-1a74-464d-aef2-3a4f91a5cdda' # Images
      targetSiteId: null
      validateRelatedElements: true
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  d80ee1f4-e752-4e38-860a-c5f26790bf89: # Caption
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: caption
    instructions: 'Leave blank to show the image''s title'
    name: Caption
    searchable: true
    settings:
      byteLimit: null
      charLimit: 30
      code: false
      columnType: string
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: image
name: Image
sortOrder: 3
