field: 58b2e318-26cc-47b8-bee2-81369731d72f # Body Content
fieldLayouts:
  d199692c-613e-45e8-9209-271e3b228c21:
    tabs:
      -
        elements:
          -
            fieldUid: a6d13a9f-d4ed-41e5-be7f-c93dcb679633 # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5966dedf-4e96-4924-9494-3deb477adbda
            warning: null
            width: 100
        name: Content
        uid: 4d5f2ecd-4143-4ad6-89ac-e73b3fed6a70
fields:
  a6d13a9f-d4ed-41e5-be7f-c93dcb679633: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: 'You can use markdown and reference tags here, but html tags are stripped off.'
    name: Text
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: text
name: Text
sortOrder: 2
