fieldLayouts:
  a1ae8d99-a94b-4652-9c5e-cce1445acb84:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0d7a4c99-a44b-4959-98a0-c3e505a42528
            warning: null
            width: 100
          -
            fieldUid: 9a302fae-a3bf-4298-8a06-24f8c8f6f335 # Featured Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4bcd3dcb-421c-49a5-b451-518c0955fcb8
            warning: null
            width: 100
          -
            fieldUid: 3ef62a7b-6c6d-470f-88a6-31de5a099b38 # Teaser
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 21e16428-f6f3-40e5-bb2d-49513d140e71
            warning: null
            width: 100
          -
            fieldUid: 58b2e318-26cc-47b8-bee2-81369731d72f # Body Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 594c4a85-ef84-47c8-8000-32533b93b6b1
            warning: null
            width: 100
        name: Content
        uid: 971e6d79-cdd5-4536-b737-1f8df3e62b2d
handle: home
hasTitleField: true
name: Home
section: 2c476892-24a5-43a5-ae3a-70f4609382e3 # Home
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: language
