fieldLayouts:
  930449b7-c7f2-4fc4-87ec-37bcc083b0e7:
    tabs:
      -
        elements:
          -
            heading: Header
            type: craft\fieldlayoutelements\Heading
            uid: 561b19f0-cea0-4b0d-b6a2-bdfbc9e15378
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f29c4c36-92a2-4602-b543-2d8e9ba3b807
            warning: null
            width: 100
          -
            fieldUid: 9a302fae-a3bf-4298-8a06-24f8c8f6f335 # Featured Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2e4a7373-1f4a-4582-90eb-2b4d6b8c18b4
            warning: null
            width: 25
          -
            fieldUid: 3ef62a7b-6c6d-470f-88a6-31de5a099b38 # Teaser
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e507047-9588-4d75-bd1b-1c0fab354cfc
            warning: null
            width: 75
          -
            heading: Content
            type: craft\fieldlayoutelements\Heading
            uid: fa17d1c9-65ea-48c1-bf52-eb08fc943c37
          -
            fieldUid: 58b2e318-26cc-47b8-bee2-81369731d72f # Body Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 962ff8cf-b176-4a6c-946f-63d2636ac87e
            warning: null
            width: 100
          -
            heading: Relations
            type: craft\fieldlayoutelements\Heading
            uid: 12fcb62d-0b2c-4942-9e5e-a0c4a47fe0dd
          -
            fieldUid: 9b2aaaa8-c827-4881-955a-86f2df0ea79c # Related Entries
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b445753c-2706-44bc-b244-07059742977d
            warning: null
            width: 100
        name: Content
        uid: b5b61cc8-ba99-41c6-9264-bb36d8743d63
handle: page
hasTitleField: true
name: Page
section: 09f97fdd-45fe-4221-982a-a2077c8460b1 # Page
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
