columnSuffix: null
contentColumnType: string
fieldGroup: fea375f0-9f46-4952-b272-2dcf42b0cce5 # Site Info
handle: copyright
instructions: null
name: Copyright
searchable: true
settings:
  byteLimit: null
  charLimit: 100
  code: false
  columnType: string
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
