columnSuffix: null
contentColumnType: string
fieldGroup: fea375f0-9f46-4952-b272-2dcf42b0cce5 # Site Info
handle: footerNavigation
instructions: null
name: 'Footer Navigation'
searchable: false
settings:
  allowSelfRelations: false
  localizeRelations: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: true
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
