fieldLayouts:
  958d9c22-9855-40ef-b9cf-16af08de416b:
    tabs:
      -
        elements:
          -
            fieldUid: 64c37a78-14f3-4dba-874a-4d4bdd5ba1ee # Site Name
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d1aeb77-5456-40ef-b642-421511d21837
            warning: null
            width: 100
          -
            fieldUid: 2a586bbf-019e-4c87-bc15-d0b5db0efc98 # Site Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7eef2871-9833-4a45-8cbc-74d27ba03685
            warning: null
            width: 25
          -
            fieldUid: 3f9c2f2a-8ab0-4aba-bf4e-02d5336d14c0 # Copyright
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d582eb4d-6ee6-4eb5-a6f8-c110d6b69fa7
            warning: null
            width: 100
          -
            fieldUid: 72fdc33e-481f-40c0-80ad-c531e3a557c7 # Site Logo
            instructions: 'Currenty unused'
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dc40f882-1717-41bc-a0d6-1028622aa516
            warning: null
            width: 25
        name: 'Site Info'
        uid: 29cb568f-4c66-4a24-9262-07552e72ab2e
      -
        elements:
          -
            fieldUid: f63bb4c9-dfab-42b9-8216-531caf9f8e3f # Site Into Title
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6aa5517f-2386-473d-a1f2-047245c5113e
            warning: null
            width: 100
          -
            fieldUid: 537ad494-7b3a-48ac-8eac-b9d6384f78ab # Site Intro Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd41ff1e-a883-4f69-a4a0-7f66a7eb3c07
            warning: null
            width: 100
          -
            fieldUid: e66b59a5-0544-4803-a3e0-90a2f657eee9 # Site Intro Buttons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 908c313f-991d-484d-a52d-649da86e05d9
            warning: null
            width: 100
        name: Dashboard
        uid: d352b79f-23a0-4ae9-9544-3e13821c383a
handle: siteInfo
name: 'Site Info'
sortOrder: 2
