fieldLayouts:
  ba72cf4d-ef03-4524-8fe5-a631a85f9aca:
    tabs:
      -
        elements:
          -
            fieldUid: ae7d91c8-8743-46bb-a954-438a27946b97 # Primary Navigation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ad8fce6-f5ba-4018-a374-cea299f2b5c8
            warning: null
            width: 100
        name: Primary
        uid: a2bc894a-5976-4ccc-a1ce-f6c7f993d809
      -
        elements:
          -
            fieldUid: 15c0556c-f778-4258-ae84-ff8cef62b761 # Footer Navigation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 578328ff-ece8-4ff6-adca-83084ff644ab
            warning: null
            width: 100
        name: Footer
        uid: 82b56a32-bd5d-4407-822e-4d5166b0bd82
handle: siteNavigation
name: 'Site Navigation'
sortOrder: 3
