defaultPlacement: end
enableVersioning: true
handle: post
name: Post
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{siteUrl}?id={id}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  97e0b749-86e3-49f1-918e-9b88758928f4: # English
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
