defaultPlacement: end
enableVersioning: true
handle: topic
name: Topic
propagationMethod: all
siteSettings:
  97e0b749-86e3-49f1-918e-9b88758928f4: # English
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
